name: simplenote
version: v1.1.0
summary: The simplest way to keep notes.
description: |
 Simplenote is an easy way to keep notes, lists, ideas and more. Your
 notes stay in sync with all of your devices for free.

grade: stable
confinement: strict

parts:
  simplenote:
    plugin: dump
    source: https://github.com/Automattic/simplenote-electron/releases/download/v1.1.0/Simplenote-linux-1.1.0.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=simplenote|Icon=/usr/share/pixmaps/simplenote\.png|' usr/share/applications/simplenote.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  simplenote:
    command: bin/desktop-launch $SNAP/usr/share/simplenote/simplenote
    desktop: usr/share/applications/simplenote.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - pulseaudio
      - unity7
      - wayland
